### ISSUE TITLE
Image comparison algorithms

### ISSUE THREAD

**Issue by dngoodman** [CSC545-TEAM-RED/PROJECT-X#2]
Histogram matching - get sums of colors from both images and compare them

**Comment by dngoodman** [comment]
Palette match - generate a palette from both images and compare the resultant palettes

**Comment by dngoodman** [comment]
Direct pixel match - compare the pixels in both images

**Comment by dngoodman** [comment]
Keypoint matching - find areas of high importance in an image

**Comment by shaneallgeier** [comment]
Duplicate of #3
